### ISSUE TITLE
Hardocded references to Kids First

### ISSUE THREAD

**Issue by jecos** [ncpi-fhir/ncpi-fhir-utility#27]
There is some hardcoded references to Kids First : https://github.com/ncpi-fhir/ncpi-fhir-utility/blob/3220939ea91ae7b78e01468ae025f9881ba416b9/ncpi_fhir_utility/app.py#L432-L433

**Comment by znatty22** [comment]
There are also lots of left over references to Kids First in the test IG (tests/data/site_root) that need to be fixed.
